services:
  # ===== #
  # MYSQL #
  # ===== #
  mysql:
    image: mysql:8
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_R}
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-net
  # ====== #
  # VENTAS #
  # ====== #
  backend-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:${DB_PORT}/${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 40s
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - front-net
      - back-net
  # ========= #
  # DESPACHOS #
  # ========= #
  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./.env
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      DATASOURCE_URL_D: jdbc:mysql://mysql:${DB_PORT}/${DB_NAME_D}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME_D}
      DB_USERNAME: ${DB_USERNAME_D}
      DB_PASSWORD: ${DB_PASSWORD_D}
    depends_on:
      mysql:
        condition: service_healthy
      backend-ventas:
        condition: service_healthy
    networks:
      - front-net
      - back-net
  # ======== #
  # FRONTEND #
  # ======== #
  frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    user: "${CURRENT_UID}:${CURRENT_GID}"
    env_file:
      - ./.env
    environment:
      HOST: 0.0.0.0
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - front-net
# ================== #
# VOLUMES & NETWORKS #
# ================== #
volumes:
  mysql_data:
networks:
  front-net:
    driver: bridge
  back-net:
    driver: bridge
