name: CI Pipeline
# Acciones que ejecutan el archivo
on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy
# jobs: trabajos a ejecutar
jobs:
  # =================================== #
  # FASE 1: INTEGRACIÓN - FRONT-TESTING #
  # =================================== #
  front-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front_despacho
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --include=dev

    - name: Ejecutar tests del frontend
      env:
        CI: true
      run: npm run test
  # ================= #
  # FRONTEND BUILDING #
  # ================= #
  front-build:
    needs: front-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front_despacho
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup node (instalar node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install --include=dev
      
      - name: run build
        run: npm run build
  # ====================== #
  # BACKEND VENTAS TESTING #
  # ====================== #
  back-Venta-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-Ventas_SpringBoot/Springboot-API-REST
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "root_ci"
          MYSQL_DATABASE: innovatech_ventas_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4
      - name: Config JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Ejecutar test del backend
        run: |
          mvn clean test \
          -Dspring.profiles.active=test \
          "-Dspring.datasource.url=jdbc:mysql://localhost:3306/innovatech_ventas_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true" \
          -Dspring.datasource.username=root \
          -Dspring.datasource.password=root_ci
  # ======================= #
  # BACKEND VENTAS BUILDING #
  # ======================= #
  back-Venta-build:
    needs: back-Venta-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-Ventas_SpringBoot/Springboot-API-REST
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4
      - name: Config JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Empaquetar Aplicación
        run: mvn clean package -DskipTests
  # ========================= #
  # BACKEND DESPACHOS TESTING #
  # ========================= #
  back-Despacho-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "root_ci"
          MYSQL_DATABASE: innovatech_despachos_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4
      - name: Config JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Ejecutar test del backend
        run: |
          mvn clean test \
          -Dspring.profiles.active=test \
          "-Dspring.datasource.url=jdbc:mysql://localhost:3306/innovatech_despachos_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true" \
          -Dspring.datasource.username=root \
          -Dspring.datasource.password=root_ci
  # ========================== #
  # BACKEND DESPACHOS BUILDING #
  # ========================== #
  back-Despacho-build:
    needs: back-Despacho-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4
      - name: Config JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Empaquetar Aplicación
        run: mvn clean package -DskipTests
  # ================== #
  # FASE 2: DESPLIEGUE #
  # ================== #

  # proximamnete.